// Generated by Wrangler on Fri Jun 14 2024 18:22:35 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	PET_STATUS: KVNamespace;
	TOKEN_KEY: string;
	SALT: string;
	PET_D1: D1Database;
}
