#:schema node_modules/wrangler/config-schema.json
name = "pet-backend"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "PET_D1"
database_name = "pet-d1"
database_id = "7ad343d3-ba12-4cc1-abb3-8debcdc9ab39"

[[kv_namespaces]]
binding = "PET_STATUS"
id = "d5f38cf3b09b49f498829445e69462cf"

